version: "3"

networks:
  crypto-net:
    driver: bridge

volumes:
  influxdb-data:

services:
  bfxstore:
    container_name: bfxstore
    build: .
    restart: always
    networks:
      - crypto-net
    environment:
      BACKEND: INFLUX
      HOST: http://influxdb:8086
      ORG: etrading
      BUCKET: cryptobucket
      TOKEN: aZGy6sVTQwaM02tcrH08yWl1h8pX8NkSJTkO7F7ZebjLO5pZJ_KsUKxFG-KQ3QJ9edfFT30iDz2nUBl8FHFk4g==
      EXCHANGE: BITFINEX
      SYMBOLS: BTC-USD,ETH-USD,LEO-USD
      CHANNELS: trades,ticker 
  influxdb:
    container_name: influxdb
    image: influxdb:2.7-alpine
    restart: always
    networks:
      - crypto-net
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: cryptostore
      DOCKER_INFLUXDB_INIT_PASSWORD: 83CrptstPwd66
      DOCKER_INFLUXDB_INIT_ORG: etrading
      DOCKER_INFLUXDB_INIT_BUCKET: cryptobucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: auth-token-83CrptstPwd66
    volumes:
      - influxdb-data:/var/lib/influxdb2
