version: "3"

networks:
  crypto-net:
    driver: bridge

volumes:
  influxdb-data:
  # grafana-data:

services:
  bfxstore:
    container_name: bfxstore
    build: .
    restart: always
    networks:
      - crypto-net
    environment:
      BACKEND: INFLUX
      HOST: http://influxdb:8086
      ORG: etrading
      BUCKET: cryptobucket
      TOKEN: UIN0iIPYjJIusOvU-H65NifsnuvAA62yv3nmBO4mfSXu0PgpYttCge0Pkh3gf_dsnEEfZDEM0wdorwuHg3BAkw==
      EXCHANGE: BINANCE_FUTURES
      SYMBOLS: BTC-USDT-PERP
      CHANNELS: open_interest,funding,ticker 
  influxdb:
    container_name: influxdb
    image: influxdb:2.7-alpine
    restart: always
    networks:
      - crypto-net
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: cryptostore
      DOCKER_INFLUXDB_INIT_PASSWORD: 83CrptstPwd66
      DOCKER_INFLUXDB_INIT_ORG: etrading
      DOCKER_INFLUXDB_INIT_BUCKET: cryptobucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: auth-token-83CrptstPwd66
    volumes:
      - influxdb-data:/var/lib/influxdb2
  # grafana:
  #   image: grafana/grafana-enterprise
  #   networks:
  #     - crypto-net
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - grafana-data:/var/lib/grafana